# Generated by Django 3.0.5 on 2020-04-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=40)),
                ('question_level', models.IntegerField(default=1)),
                ('question_text', models.CharField(max_length=600)),
                ('cin_format', models.CharField(max_length=300)),
                ('cout_format', models.CharField(max_length=300)),
                ('data_range', models.CharField(max_length=300)),
                ('cin_example', models.CharField(max_length=100)),
                ('cout_example', models.CharField(max_length=100)),
            ],
        ),
    ]
