# Generated by Django 3.0.5 on 2020-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_lable',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_source',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
