# Generated by Django 3.0.5 on 2020-04-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200405_2237'),
        ('algo', '0003_auto_20200407_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='memory_restrict',
            field=models.IntegerField(default=65536),
        ),
        migrations.AddField(
            model_name='question',
            name='time_restrict',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('code', models.TextField(max_length=2000)),
                ('cout', models.TextField(max_length=2000)),
                ('lang', models.TextField(max_length=10)),
                ('time', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Question')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
    ]
