# Generated by Django 3.0.5 on 2020-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_auto_20200412_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='test_path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
