# Generated by Django 3.0.5 on 2020-04-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_auto_20200413_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_cnt',
            new_name='test_total',
        ),
    ]
