# Generated by Django 3.0.5 on 2020-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0007_auto_20200414_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='memory',
            new_name='memoryused',
        ),
        migrations.RemoveField(
            model_name='record',
            name='cout',
        ),
        migrations.AddField(
            model_name='record',
            name='timeused',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
