# Generated by Django 3.0.5 on 2020-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0008_auto_20200416_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
