# Generated by Django 3.0.5 on 2020-04-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200405_2237'),
        ('algo', '0010_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='q_id',
        ),
        migrations.AddField(
            model_name='solution',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sol_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('text', models.TextField()),
                ('sol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Solution')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
    ]
