# Generated by Django 3.0.5 on 2020-04-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0012_auto_20200417_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='u_id',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='source',
            new_name='source_link',
        ),
        migrations.AddField(
            model_name='solution',
            name='qid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='sol_comment',
            name='sol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Solution'),
        ),
    ]
