# Generated by Django 3.0.5 on 2020-04-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200405_2237'),
        ('algo', '0014_auto_20200417_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sol_comment',
            name='sol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Solution'),
        ),
        migrations.CreateModel(
            name='Sol_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField(default=0)),
                ('sol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Solution')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
    ]
