# Generated by Django 3.0.5 on 2020-04-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0015_auto_20200417_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sol_comment',
            name='sol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Solution'),
        ),
        migrations.AlterField(
            model_name='sol_vote',
            name='sol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Solution'),
        ),
    ]
